#############################################################################
##         _    _
##    _ __| | _| |
##   | '__| |/ / |   Richard Klein Leugemors
##   | |  |   <| |   https://www.github.com/leugemors/
##   |_|  |_|\_\_|
##
##   Configuration for Alacritty, the GPU enhanced terminal emulator
##
#############################################################################

[general]
import = [
    # "~/.config/alacritty/themes/catppuccin_latte.toml",
    # "~/.config/alacritty/themes/catppuccin_frappe.toml",
    # "~/.config/alacritty/themes/catppuccin_macchiato.toml",
    # "~/.config/alacritty/themes/catppuccin_mocha.toml",
    # "~/.config/alacritty/themes/doom_one.toml",
    # "~/.config/alacritty/themes/dracula.toml",
    # "~/.config/alacritty/themes/dracula_plus.toml",
    # "~/.config/alacritty/themes/gruvbox_harddark.toml",
    # "~/.config/alacritty/themes/monokai_charcoal.toml",
    # "~/.config/alacritty/themes/nord.toml",
    # "~/.config/alacritty/themes/one_dark.toml",
    "~/.config/alacritty/themes/rose_pine.toml",
    "~/.config/alacritty/keybindings.toml",
]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[scrolling]
history = 5000

[window]
decorations = "None"    # Full, Transparent, Buttonless, None
dynamic_padding = true
opacity = 1.00          # Opacity can also be set via picom
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 3
y = 3

# For some odd reason I need to set half te value of the font size I want
# hier
[font]
size = 8.0
# size = 6.5

[font.offset]
x = 0
y = 2

[font.normal]
style = "Regular"
# family = "3270 Nerd Font"
# family = "FiraCode Nerd Font"
# family = "Hack Nerd Font"
family = "JetBrains Mono Nerd Font"
# family = "Literation Mono Nerd Font"
# family = "RobotoMono Nerd Font"
# family = "Space Mono Nerd Font"
# family = "Ubuntu Mono Nerd Font"

# [font.bold]
# style = "Bold"
# family = "Source Code Pro"

# [font.italic]
# style = "Italic"
# family = "Source Code Pro"

# [font.bold_italic]
# style = "Bold Italic"
# family = "Source Code Pro"

[selection]
save_to_clipboard = true

### eof #####################################################################
